---
kind: pipeline
name: lint
type: docker
steps:
- name: mod tidy
  image: "pr0ger/baseimage:build.go-latest"
  commands:
  - go mod tidy -v
  - git diff --exit-code
- name: lint
  image: "golangci/golangci-lint:v1.32-alpine"
  commands:
  - go get github.com/golang/mock/mockgen@latest
  - go get -u github.com/reviewdog/reviewdog/cmd/reviewdog@v0.11.0
  - go generate -x
  - golangci-lint run -v | reviewdog -reporter=github-check
  environment:
    REVIEWDOG_TOKEN:
      from_secret: reviewdog_token

---
kind: pipeline
name: tests 1.13
type: docker
steps:
- name: build
  image: "pr0ger/baseimage:build.go-1.13"
  commands:
  - go get github.com/golang/mock/mockgen@latest
  - go generate -x
  - go build
  volumes:
  - name: deps
    path: /go
- name: test
  image: "pr0ger/baseimage:build.go-1.13"
  commands:
  - go test -v ./...
  volumes:
  - name: deps
    path: /go

volumes:
- name: deps
  temp: { }

---
kind: pipeline
name: update docs
type: docker
clone:
  disable: true
trigger:
  event:
  - tag
steps:
- name: pkg.go.dev
  image: "alpine:latest"
  commands:
  - apk add curl jq
  - curl -s https://proxy.golang.org/go.pr0ger.dev/logger/@v/${DRONE_TAG}.info | jq
