linters:
  presets:
  - bugs
  - format
  - performance
  - unused
  enable:
  - dupl
  - gochecknoglobals
  - gochecknoinits
  - goconst
  - gocritic
  - godox
  - golint
  - gosimple
  - interfacer
  - lll
  - misspell
  - nakedret
  - stylecheck
  - unconvert
  - whitespace

linters-settings:
  errcheck:
    exclude: .errcheck_excludes.txt
  lll:
    tab-width: 4
