linters:
  presets:
  - bugs
  - complexity
  - format
  - performance
  - style
  - unused
  disable:
  - depguard
  - funlen
  - godot
  - gomnd
  - gomodguard
  - testpackage
  - wsl
linters-settings:
  dogsled:
    max-blank-identifiers: 3
    errcheck:
      exclude: .errcheck_excludes.txt
    lll:
      tab-width: 4
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - goerr113
