linters:
  presets:
  - bugs        # bugs detection
  - comment     # comments analysis
  - complexity  # code complexity analysis
  - error       # error handling analysis
  - format      # code formatting
  # - import    # imports analysis
  - metalinter  # linter that contains multiple rules or multiple linters
  #  - module   # Go modules analysis
  - performance # performance
  - sql         # SQL
  # - style     # coding style
  # - test      # the analysis of the code of the tests
  - unused
  enable:
  # module; depguard & gomodguard is useless in almost any project
  - gomoddirectives
  # style preset
  - asciicheck
  - canonicalheader
  - containedctx
  - dogsled
  - dupl
  - errname
  - forcetypeassert
  - gochecknoglobals
  - gochecknoinits
  - goconst
  - godox
  - goprintffuncname
  - gosimple
  - lll
  - makezero
  - nakedret
  - nolintlint
  - nosprintfhostport
  - predeclared
  - promlinter
  - stylecheck
  - tagliatelle
  - thelper
  - tparallel
  - unconvert
  - whitespace
  - wastedassign
linters-settings:
  dogsled:
    max-blank-identifiers: 3
  errcheck:
    exclude-functions:
    - (net/http.ResponseWriter).Write
    - github.com/go-chi/render.Render
    - github.com/go-chi/render.RenderList
  errorlint:
    errorf: true
  funlen:
    lines: 100
    statements: 60
  gci:
    sections:
    - standard
    - default
    - prefix(go.pr0ger.dev/logger)
  godot:
    scope: declarations
  goimports:
    local-prefixes: go.pr0ger.dev/logger
  gomoddirectives:
    replace-local: true
    retract-allow-no-explanation: false
  lll:
    tab-width: 4
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
  - path: _test\.go
    linters:
    - dupl
    - goerr113
    - forcetypeassert
  # excluded here to not mess up with the the code example in docs
  - path: doc_test.go
    text: 'G112'
