pull_request_rules:
- name: automatic merge for Dependabot pull requests
  conditions:
  - "#approved-reviews-by>=1"
  - author~=^dependabot\[bot\]$
  - status-success=continuous-integration/drone/pr
  - status-success=continuous-integration/drone/push
  actions:
    merge:
      method: squash
