name: go mod tidy

on:
  pull_request:
    types: 
    - opened

jobs:
  tidy:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go
      with:
        go-version: '1.*'
        stable: 'true'

    - run: go mod tidy -v
    
    - name: commit
      run: |
        git add go.sum
        git commit --amend --no-edit

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
